console.log("1..");
var bankName;
console.log("before initilize");
console.log(bankName);
bankName="SBI Bank";
console.log("after initilize");
console.log(bankName);
console.log(typeof bankName);
console.log("2..");
var marks= '90%';
console.log(typeof marks);
console.log("3..");
var isWorking;
console.log("before initilize");
console.log(isWorking);
isWorking=true;
console.log("after initilize");
console.log(isWorking);
console.log(typeof isWorking);
console.log("4..");
var totalCount="Hundred and Seven";
console.log(typeof totalCount);
totalCount=107;
console.log(typeof totalCount);
